### ISSUE TITLE
Two same variable define?

### ISSUE THREAD

**Issue by tumashu** [yanghaoxie/which-key-posframe#4]
https://github.com/yanghaoxie/which-key-posframe/blob/e2f723fbee19c722f0202d74c5bc0af0e9a5fd82/which-key-posframe.el#L61

**Comment by yanghaoxie** [comment]
Haha! Pasted twice when steal code from you `ivy-posframe`.

**Comment by tumashu** [comment]
haha, by the way,  (face-attribute xxx :foreground nil t) is better

**Comment by yanghaoxie** [comment]
Thanks, fixed in e7f28608c7fc9507e407c6b840dff09062df533a
